//! Claude Code hook injection utilities
//!
//! Handles writing hook scripts and updating settings.json.
//! When a session is created, Woodchuck automatically configures Claude Code
//! hooks to report status changes via HTTP.
//!
//! Hooks are injected per-project, writing to `<project-folder>/.claude/`.

use std::path::{Path, PathBuf};

use tokio::fs;

use crate::model::ModelError;

/// Validate that the external URL is safe to embed in a bash script.
///
/// # Errors
/// Returns `ModelError::HookInjection` if the URL:
/// - Does not start with http:// or https://
/// - Contains shell metacharacters that could enable injection
fn validate_external_url(url: &str) -> Result<(), ModelError> {
    // Must be http or https
    if !url.starts_with("http://") && !url.starts_with("https://") {
        return Err(ModelError::HookInjection(
            "external_url must start with http:// or https://".to_string(),
        ));
    }
    // Must not contain shell metacharacters
    let forbidden = ['$', '`', '"', '\'', '\\', ';', '|', '&', '\n', '\r'];
    if url.chars().any(|c| forbidden.contains(&c)) {
        return Err(ModelError::HookInjection(
            "external_url contains forbidden characters".to_string(),
        ));
    }
    Ok(())
}

/// Generate the hook script content with the given external URL
fn generate_hook_script(external_url: &str) -> String {
    format!(
        r#"#!/bin/bash
# Woodchuck hook script - reports Claude Code events to the backend
# Auto-generated by Woodchuck. Do not edit manually.

# Requires jq for JSON parsing
if ! command -v jq &>/dev/null; then
  exit 0
fi

# Read JSON input from stdin
INPUT=$(cat)

SESSION_ID="${{CLAUDE_SESSION_ID:-}}"
WOODCHUCK_URL="${{WOODCHUCK_URL:-{external_url}}}"
EVENT_TYPE=$(echo "$INPUT" | jq -r '.hook_event_name // empty')

case "$EVENT_TYPE" in
  Stop)
    HOOK_EVENT="done"
    ;;
  Notification)
    NOTIFICATION_TYPE=$(echo "$INPUT" | jq -r '.notification_type // empty')
    if [ "$NOTIFICATION_TYPE" = "idle_prompt" ] || [ "$NOTIFICATION_TYPE" = "permission_prompt" ]; then
      HOOK_EVENT="waiting"
    else
      exit 0
    fi
    ;;
  *)
    exit 0
    ;;
esac

if [ -z "$SESSION_ID" ]; then
  exit 0
fi

curl -s -X POST \
  "${{WOODCHUCK_URL}}/api/sessions/${{SESSION_ID}}/hook" \
  -H "Content-Type: application/json" \
  -d "{{\\"event\\": \\"${{HOOK_EVENT}}\\"}}" \
  --max-time 2 \
  >/dev/null 2>&1 &

exit 0
"#,
        external_url = external_url
    )
}

/// Ensure the hook script exists at `<project_folder>/.claude/woodchuck-hook.sh`
///
/// Creates or updates the hook script with the correct external URL.
/// The script is made executable (on Unix systems).
///
/// # Arguments
/// * `project_folder` - The project folder path where the session is running
/// * `external_url` - The Woodchuck backend URL (e.g., "http://localhost:3000")
///
/// # Errors
/// Returns `ModelError::HookInjection` if any file operation fails.
async fn ensure_hook_script(project_folder: &str, external_url: &str) -> Result<PathBuf, ModelError> {
    let claude_dir = PathBuf::from(project_folder).join(".claude");
    let script_path = claude_dir.join("woodchuck-hook.sh");

    // Check for symlink attack: if .claude exists as a symlink, refuse to write
    if claude_dir.is_symlink() {
        return Err(ModelError::HookInjection(
            ".claude directory is a symlink, refusing to write hooks".to_string(),
        ));
    }

    // Ensure .claude directory exists in the project folder
    fs::create_dir_all(&claude_dir).await.map_err(|e| {
        ModelError::HookInjection(format!(
            "Failed to create .claude directory: {}",
            e
        ))
    })?;

    // Write hook script (always overwrite to ensure latest version)
    let script_content = generate_hook_script(external_url);
    fs::write(&script_path, &script_content).await.map_err(|e| {
        ModelError::HookInjection(format!(
            "Failed to write hook script to {}: {}",
            script_path.display(),
            e
        ))
    })?;

    // Make executable (Unix only)
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        let mut perms = fs::metadata(&script_path)
            .await
            .map_err(|e| ModelError::HookInjection(format!("Failed to get permissions: {}", e)))?
            .permissions();
        perms.set_mode(0o755);
        fs::set_permissions(&script_path, perms)
            .await
            .map_err(|e| ModelError::HookInjection(format!("Failed to set permissions: {}", e)))?;
    }

    Ok(script_path)
}

/// Inject Woodchuck hooks into Claude Code configuration for a specific project.
///
/// This function:
/// 1. Validates the external URL to prevent shell injection
/// 2. Ensures the hook script exists at `<project_folder>/.claude/woodchuck-hook.sh`
/// 3. Updates `<project_folder>/.claude/settings.json` to reference the hook script
///
/// # Arguments
/// * `session_id` - Used only for logging context
/// * `project_folder` - The project folder path where the session is running
/// * `external_url` - The Woodchuck backend URL (e.g., "http://localhost:3000")
///
/// # Errors
/// Returns `ModelError::HookInjection` if URL validation or any file operation fails.
pub async fn inject_hooks(session_id: &str, project_folder: &str, external_url: &str) -> Result<(), ModelError> {
    // 1. Validate external URL to prevent shell injection
    validate_external_url(external_url)?;

    // 2. Ensure hook script exists in the project's .claude directory
    let script_path = ensure_hook_script(project_folder, external_url).await?;

    // 3. Update settings.json in the project's .claude directory
    let claude_dir = PathBuf::from(project_folder).join(".claude");
    let settings_path = claude_dir.join("settings.json");
    update_settings_json(&settings_path, &script_path).await?;

    // 4. Inject inbox instructions so sessions know how to report issues
    inject_inbox_instructions(&claude_dir, external_url).await?;

    tracing::info!(session = %session_id, project_folder = %project_folder, "Injected Woodchuck hooks");
    Ok(())
}

/// Check if our hook is already present in the nested structure
fn hook_already_present(arr: &[serde_json::Value], script_str: &str) -> bool {
    arr.iter().any(|matcher_obj| {
        matcher_obj
            .get("hooks")
            .and_then(|h| h.as_array())
            .map(|inner_hooks| {
                inner_hooks.iter().any(|hook| {
                    hook.get("command")
                        .and_then(|c| c.as_str())
                        .map(|cmd| cmd == script_str)
                        .unwrap_or(false)
                })
            })
            .unwrap_or(false)
    })
}

/// Update settings.json to include hook references
async fn update_settings_json(settings_path: &Path, script_path: &Path) -> Result<(), ModelError> {
    let script_str = script_path.to_string_lossy();

    // Read existing settings or start with empty object
    let mut settings: serde_json::Value = match fs::read_to_string(settings_path).await {
        Ok(content) => serde_json::from_str(&content).map_err(|e| {
            ModelError::HookInjection(format!("Failed to parse settings.json: {}", e))
        })?,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => serde_json::json!({}),
        Err(e) => {
            return Err(ModelError::HookInjection(format!(
                "Failed to read settings.json: {}",
                e
            )))
        }
    };

    // Ensure hooks object exists
    if !settings.get("hooks").map(|v| v.is_object()).unwrap_or(false) {
        settings["hooks"] = serde_json::json!({});
    }

    let hooks = settings["hooks"].as_object_mut().unwrap();

    // Create the nested hook entry structure:
    // { "matcher": "", "hooks": [{ "type": "command", "command": "/path/to/script.sh" }] }
    let hook_entry = serde_json::json!({
        "matcher": "",
        "hooks": [{
            "type": "command",
            "command": script_str.to_string()
        }]
    });

    // Add script to Stop and Notification hooks (without duplicating)
    for hook_type in &["Stop", "Notification"] {
        let arr = hooks
            .entry(*hook_type)
            .or_insert_with(|| serde_json::json!([]))
            .as_array_mut()
            .ok_or_else(|| {
                ModelError::HookInjection(format!("hooks.{} is not an array", hook_type))
            })?;

        // Only add if not already present (check nested structure)
        if !hook_already_present(arr, &script_str) {
            arr.push(hook_entry.clone());
        }
    }

    // Write back with pretty formatting
    let content = serde_json::to_string_pretty(&settings).map_err(|e| {
        ModelError::HookInjection(format!("Failed to serialize settings.json: {}", e))
    })?;

    fs::write(settings_path, content).await.map_err(|e| {
        ModelError::HookInjection(format!("Failed to write settings.json: {}", e))
    })?;

    Ok(())
}

/// The inbox instructions filename written inside `.claude/`
const INBOX_INSTRUCTIONS_FILENAME: &str = "woodchuck-inbox.md";

/// Marker line used to detect if inbox instructions are already present in CLAUDE.md
const INBOX_MARKER: &str = "<!-- woodchuck-inbox -->";

/// Generate inbox instruction content
fn generate_inbox_instructions(external_url: &str) -> String {
    format!(
        r#"{marker}
## Woodchuck Self-Healing

You are running inside a woodchuck-managed session. If you encounter any of the following:
- A bug in the woodchuck terminal (display glitches, input issues, resize problems)
- An error from the woodchuck API or WebSocket
- An idea to improve the woodchuck experience

You can report it by writing a markdown file to `~/.woodchuck/inbox/`:
- Filename: `YYYYMMDD-HHMMSS-{{description}}.md`
- Content: describe the issue clearly with reproduction steps if applicable

Or use the API:
```bash
curl -s -X POST {url}/api/maintainer/inbox \
  -H "Content-Type: application/json" \
  -d '{{"source":"$CLAUDE_SESSION_ID","type":"bug","message":"description"}}'
```

The woodchuck maintainer will pick it up and fix it automatically.
"#,
        marker = INBOX_MARKER,
        url = external_url,
    )
}

/// Inject inbox instructions into the project's `.claude/` directory.
///
/// Appends inbox instructions to `CLAUDE.md` if not already present.
/// Creates the file if it doesn't exist.
async fn inject_inbox_instructions(claude_dir: &Path, external_url: &str) -> Result<(), ModelError> {
    let claude_md_path = claude_dir.join("CLAUDE.md");

    // Refuse to write if CLAUDE.md is a symlink
    if claude_md_path.is_symlink() {
        return Err(ModelError::HookInjection(
            "CLAUDE.md is a symlink, refusing to write".to_string(),
        ));
    }

    // Read existing content
    let existing = match fs::read_to_string(&claude_md_path).await {
        Ok(content) => content,
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => String::new(),
        Err(e) => {
            return Err(ModelError::HookInjection(format!(
                "Failed to read CLAUDE.md: {}",
                e
            )))
        }
    };

    // Skip if already injected
    if existing.contains(INBOX_MARKER) {
        return Ok(());
    }

    // Append inbox instructions
    let instructions = generate_inbox_instructions(external_url);
    let new_content = if existing.is_empty() {
        instructions
    } else {
        format!("{}\n\n{}", existing.trim_end(), instructions)
    };

    fs::write(&claude_md_path, new_content).await.map_err(|e| {
        ModelError::HookInjection(format!("Failed to write CLAUDE.md: {}", e))
    })?;

    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn test_hook_script_is_valid_bash() {
        let script = generate_hook_script("http://localhost:3000");
        // Basic syntax check: script should start with shebang
        assert!(script.starts_with("#!/bin/bash"));
        // Should check for jq
        assert!(script.contains("command -v jq"));
        // Should read from stdin
        assert!(script.contains("INPUT=$(cat)"));
        // Should parse hook_event_name from JSON
        assert!(script.contains("jq -r '.hook_event_name // empty'"));
        // Should contain the event handling
        assert!(script.contains("case \"$EVENT_TYPE\""));
        assert!(script.contains("Stop)"));
        assert!(script.contains("Notification)"));
        // Should parse notification_type for Notification events
        assert!(script.contains("jq -r '.notification_type // empty'"));
        // Should contain the curl command
        assert!(script.contains("curl -s -X POST"));
        // Should use the external URL as default
        assert!(script.contains("http://localhost:3000"));
        // Should still use CLAUDE_SESSION_ID from environment
        assert!(script.contains("CLAUDE_SESSION_ID"));
    }

    #[test]
    fn test_hook_script_uses_custom_url() {
        let script = generate_hook_script("https://myserver.com:8080");
        assert!(script.contains("https://myserver.com:8080"));
    }

    /// Helper to verify nested hook structure
    fn verify_hook_entry(entry: &serde_json::Value, expected_command: &str) -> bool {
        entry.get("matcher").map(|m| m == "").unwrap_or(false)
            && entry
                .get("hooks")
                .and_then(|h| h.as_array())
                .map(|arr| {
                    arr.iter().any(|hook| {
                        hook.get("type").map(|t| t == "command").unwrap_or(false)
                            && hook
                                .get("command")
                                .and_then(|c| c.as_str())
                                .map(|cmd| cmd == expected_command)
                                .unwrap_or(false)
                    })
                })
                .unwrap_or(false)
    }

    #[tokio::test]
    async fn test_update_settings_creates_new_file() {
        let temp = TempDir::new().unwrap();
        let settings_path = temp.path().join("settings.json");
        let script_path = temp.path().join("hook.sh");

        update_settings_json(&settings_path, &script_path).await.unwrap();

        let content = fs::read_to_string(&settings_path).await.unwrap();
        let settings: serde_json::Value = serde_json::from_str(&content).unwrap();

        let stop_hooks = settings["hooks"]["Stop"].as_array().unwrap();
        let notif_hooks = settings["hooks"]["Notification"].as_array().unwrap();

        assert_eq!(stop_hooks.len(), 1);
        assert_eq!(notif_hooks.len(), 1);

        // Verify nested structure
        assert!(verify_hook_entry(&stop_hooks[0], &script_path.to_string_lossy()));
        assert!(verify_hook_entry(&notif_hooks[0], &script_path.to_string_lossy()));
    }

    #[tokio::test]
    async fn test_update_settings_preserves_existing() {
        let temp = TempDir::new().unwrap();
        let settings_path = temp.path().join("settings.json");
        let script_path = temp.path().join("hook.sh");

        // Pre-populate with existing settings using new nested structure
        let existing = serde_json::json!({
            "theme": "dark",
            "hooks": {
                "Stop": [{
                    "matcher": "",
                    "hooks": [{ "type": "command", "command": "/usr/local/bin/my-hook.sh" }]
                }]
            }
        });
        fs::write(&settings_path, serde_json::to_string_pretty(&existing).unwrap()).await.unwrap();

        update_settings_json(&settings_path, &script_path).await.unwrap();

        let content = fs::read_to_string(&settings_path).await.unwrap();
        let settings: serde_json::Value = serde_json::from_str(&content).unwrap();

        // Existing setting preserved
        assert_eq!(settings["theme"], "dark");
        // Existing hook preserved + new hook added
        let stop_hooks = settings["hooks"]["Stop"].as_array().unwrap();
        assert_eq!(stop_hooks.len(), 2);
        assert!(verify_hook_entry(&stop_hooks[0], "/usr/local/bin/my-hook.sh"));
        assert!(verify_hook_entry(&stop_hooks[1], &script_path.to_string_lossy()));
        // Notification hook also added
        let notif_hooks = settings["hooks"]["Notification"].as_array().unwrap();
        assert_eq!(notif_hooks.len(), 1);
        assert!(verify_hook_entry(&notif_hooks[0], &script_path.to_string_lossy()));
    }

    #[tokio::test]
    async fn test_update_settings_no_duplicate() {
        let temp = TempDir::new().unwrap();
        let settings_path = temp.path().join("settings.json");
        let script_path = temp.path().join("hook.sh");

        // Call twice
        update_settings_json(&settings_path, &script_path).await.unwrap();
        update_settings_json(&settings_path, &script_path).await.unwrap();

        let content = fs::read_to_string(&settings_path).await.unwrap();
        let settings: serde_json::Value = serde_json::from_str(&content).unwrap();

        // Should still only have one entry
        assert_eq!(settings["hooks"]["Stop"].as_array().unwrap().len(), 1);
        assert_eq!(settings["hooks"]["Notification"].as_array().unwrap().len(), 1);
    }

    #[tokio::test]
    async fn test_update_settings_handles_empty_hooks_object() {
        let temp = TempDir::new().unwrap();
        let settings_path = temp.path().join("settings.json");
        let script_path = temp.path().join("hook.sh");

        // Pre-populate with existing settings that have an empty hooks object
        let existing = serde_json::json!({
            "theme": "dark",
            "hooks": {}
        });
        fs::write(&settings_path, serde_json::to_string_pretty(&existing).unwrap()).await.unwrap();

        update_settings_json(&settings_path, &script_path).await.unwrap();

        let content = fs::read_to_string(&settings_path).await.unwrap();
        let settings: serde_json::Value = serde_json::from_str(&content).unwrap();

        assert_eq!(settings["hooks"]["Stop"].as_array().unwrap().len(), 1);
        assert_eq!(settings["hooks"]["Notification"].as_array().unwrap().len(), 1);
    }

    #[tokio::test]
    async fn test_update_settings_handles_non_object_hooks() {
        let temp = TempDir::new().unwrap();
        let settings_path = temp.path().join("settings.json");
        let script_path = temp.path().join("hook.sh");

        // Pre-populate with hooks as a non-object (invalid but we handle gracefully)
        let existing = serde_json::json!({
            "theme": "dark",
            "hooks": "invalid"
        });
        fs::write(&settings_path, serde_json::to_string_pretty(&existing).unwrap()).await.unwrap();

        update_settings_json(&settings_path, &script_path).await.unwrap();

        let content = fs::read_to_string(&settings_path).await.unwrap();
        let settings: serde_json::Value = serde_json::from_str(&content).unwrap();

        // hooks should now be an object with the arrays
        assert_eq!(settings["hooks"]["Stop"].as_array().unwrap().len(), 1);
        assert_eq!(settings["hooks"]["Notification"].as_array().unwrap().len(), 1);
    }

    #[test]
    fn test_hook_already_present_finds_nested_command() {
        let script_path = "/path/to/woodchuck-hook.sh";
        let arr = vec![serde_json::json!({
            "matcher": "",
            "hooks": [{ "type": "command", "command": script_path }]
        })];
        assert!(hook_already_present(&arr, script_path));
    }

    #[test]
    fn test_hook_already_present_returns_false_for_different_command() {
        let arr = vec![serde_json::json!({
            "matcher": "",
            "hooks": [{ "type": "command", "command": "/other/hook.sh" }]
        })];
        assert!(!hook_already_present(&arr, "/path/to/woodchuck-hook.sh"));
    }

    #[test]
    fn test_hook_already_present_handles_empty_array() {
        let arr: Vec<serde_json::Value> = vec![];
        assert!(!hook_already_present(&arr, "/path/to/hook.sh"));
    }

    #[test]
    fn test_hook_already_present_handles_malformed_entries() {
        // Old-style string entries (should not match)
        let arr = vec![serde_json::json!("/path/to/hook.sh")];
        assert!(!hook_already_present(&arr, "/path/to/hook.sh"));
    }

    // Per-project hook injection tests
    #[tokio::test]
    async fn test_ensure_hook_script_creates_in_project_folder() {
        let temp = TempDir::new().unwrap();
        let project_folder = temp.path().to_string_lossy().to_string();

        let script_path = ensure_hook_script(&project_folder, "http://localhost:3000")
            .await
            .unwrap();

        // Script should be in <project>/.claude/woodchuck-hook.sh
        let expected_path = temp.path().join(".claude").join("woodchuck-hook.sh");
        assert_eq!(script_path, expected_path);
        assert!(script_path.exists());

        // Verify script content
        let content = fs::read_to_string(&script_path).await.unwrap();
        assert!(content.starts_with("#!/bin/bash"));
        assert!(content.contains("http://localhost:3000"));
    }

    #[tokio::test]
    async fn test_inject_hooks_creates_project_local_files() {
        let temp = TempDir::new().unwrap();
        let project_folder = temp.path().to_string_lossy().to_string();

        inject_hooks("test-session", &project_folder, "http://localhost:3000")
            .await
            .unwrap();

        // Verify .claude directory was created
        let claude_dir = temp.path().join(".claude");
        assert!(claude_dir.exists());
        assert!(claude_dir.is_dir());

        // Verify hook script exists
        let script_path = claude_dir.join("woodchuck-hook.sh");
        assert!(script_path.exists());

        // Verify settings.json exists with correct hooks
        let settings_path = claude_dir.join("settings.json");
        assert!(settings_path.exists());

        let content = fs::read_to_string(&settings_path).await.unwrap();
        let settings: serde_json::Value = serde_json::from_str(&content).unwrap();
        assert!(settings["hooks"]["Stop"].as_array().unwrap().len() > 0);
        assert!(settings["hooks"]["Notification"].as_array().unwrap().len() > 0);
    }

    #[tokio::test]
    async fn test_inject_hooks_idempotent() {
        let temp = TempDir::new().unwrap();
        let project_folder = temp.path().to_string_lossy().to_string();

        // Call twice
        inject_hooks("test-session", &project_folder, "http://localhost:3000")
            .await
            .unwrap();
        inject_hooks("test-session", &project_folder, "http://localhost:3000")
            .await
            .unwrap();

        // Should still only have one hook entry per type
        let settings_path = temp.path().join(".claude").join("settings.json");
        let content = fs::read_to_string(&settings_path).await.unwrap();
        let settings: serde_json::Value = serde_json::from_str(&content).unwrap();

        assert_eq!(settings["hooks"]["Stop"].as_array().unwrap().len(), 1);
        assert_eq!(settings["hooks"]["Notification"].as_array().unwrap().len(), 1);
    }

    // URL validation tests
    #[test]
    fn test_validate_external_url_accepts_http() {
        assert!(validate_external_url("http://localhost:3000").is_ok());
        assert!(validate_external_url("http://example.com/path").is_ok());
    }

    #[test]
    fn test_validate_external_url_accepts_https() {
        assert!(validate_external_url("https://localhost:3000").is_ok());
        assert!(validate_external_url("https://example.com:8080/api").is_ok());
    }

    #[test]
    fn test_validate_external_url_rejects_non_http() {
        let result = validate_external_url("ftp://example.com");
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("http:// or https://"));
    }

    #[test]
    fn test_validate_external_url_rejects_no_scheme() {
        let result = validate_external_url("example.com");
        assert!(result.is_err());
    }

    #[test]
    fn test_validate_external_url_rejects_shell_metacharacters() {
        // Dollar sign (variable expansion)
        let result = validate_external_url("http://example.com/$HOME");
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("forbidden characters"));

        // Backtick (command substitution)
        let result = validate_external_url("http://example.com/`whoami`");
        assert!(result.is_err());

        // Semicolon (command separator)
        let result = validate_external_url("http://example.com;rm -rf /");
        assert!(result.is_err());

        // Pipe (command piping)
        let result = validate_external_url("http://example.com|cat /etc/passwd");
        assert!(result.is_err());

        // Ampersand (background/command chaining)
        let result = validate_external_url("http://example.com&echo pwned");
        assert!(result.is_err());

        // Double quote
        let result = validate_external_url("http://example.com\"");
        assert!(result.is_err());

        // Single quote
        let result = validate_external_url("http://example.com'");
        assert!(result.is_err());

        // Backslash
        let result = validate_external_url("http://example.com\\n");
        assert!(result.is_err());

        // Newline
        let result = validate_external_url("http://example.com\necho pwned");
        assert!(result.is_err());

        // Carriage return
        let result = validate_external_url("http://example.com\recho pwned");
        assert!(result.is_err());
    }

    // Inbox instruction tests

    #[tokio::test]
    async fn test_inject_inbox_instructions_creates_claude_md() {
        let temp = TempDir::new().unwrap();
        let claude_dir = temp.path().join(".claude");
        fs::create_dir_all(&claude_dir).await.unwrap();

        inject_inbox_instructions(&claude_dir, "http://localhost:3000").await.unwrap();

        let claude_md = claude_dir.join("CLAUDE.md");
        assert!(claude_md.exists());

        let content = fs::read_to_string(&claude_md).await.unwrap();
        assert!(content.contains(INBOX_MARKER));
        assert!(content.contains("woodchuck-managed session"));
        assert!(content.contains("~/.woodchuck/inbox/"));
        assert!(content.contains("http://localhost:3000/api/maintainer/inbox"));
    }

    #[tokio::test]
    async fn test_inject_inbox_instructions_appends_to_existing() {
        let temp = TempDir::new().unwrap();
        let claude_dir = temp.path().join(".claude");
        fs::create_dir_all(&claude_dir).await.unwrap();

        // Write existing CLAUDE.md
        let claude_md = claude_dir.join("CLAUDE.md");
        fs::write(&claude_md, "# My Project\n\nExisting instructions.\n").await.unwrap();

        inject_inbox_instructions(&claude_dir, "http://localhost:3000").await.unwrap();

        let content = fs::read_to_string(&claude_md).await.unwrap();
        // Existing content preserved
        assert!(content.contains("# My Project"));
        assert!(content.contains("Existing instructions."));
        // Inbox instructions appended
        assert!(content.contains(INBOX_MARKER));
    }

    #[tokio::test]
    async fn test_inject_inbox_instructions_idempotent() {
        let temp = TempDir::new().unwrap();
        let claude_dir = temp.path().join(".claude");
        fs::create_dir_all(&claude_dir).await.unwrap();

        inject_inbox_instructions(&claude_dir, "http://localhost:3000").await.unwrap();
        let first = fs::read_to_string(claude_dir.join("CLAUDE.md")).await.unwrap();

        inject_inbox_instructions(&claude_dir, "http://localhost:3000").await.unwrap();
        let second = fs::read_to_string(claude_dir.join("CLAUDE.md")).await.unwrap();

        // Content should be identical (not duplicated)
        assert_eq!(first, second);
    }

    #[test]
    fn test_generate_inbox_instructions_contains_url() {
        let content = generate_inbox_instructions("https://my-server.com:8080");
        assert!(content.contains("https://my-server.com:8080/api/maintainer/inbox"));
    }

    #[tokio::test]
    async fn test_inject_hooks_includes_inbox_instructions() {
        let temp = TempDir::new().unwrap();
        let project_folder = temp.path().to_string_lossy().to_string();

        inject_hooks("test-session", &project_folder, "http://localhost:3000")
            .await
            .unwrap();

        // Verify CLAUDE.md was created with inbox instructions
        let claude_md = temp.path().join(".claude").join("CLAUDE.md");
        assert!(claude_md.exists());
        let content = fs::read_to_string(&claude_md).await.unwrap();
        assert!(content.contains(INBOX_MARKER));
    }
}
